djangoproj/mysite/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^shop/', include('shop.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'', include('shop.urls')),]

djangoproj/mysite/shop/urls.py
from django.conf.urls import url

from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'
urlpatterns = [url(r'^$', views.index, name='index'),
               url(r'^cart/$', views.bought, name='bought'),
               url(r'^add_to_cart/$', views.add_to_cart, name= 'add_to_cart'),]\
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoproj/mysite/shop/models.py
from __future__ import unicode_literals

# Create your models here.
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone
import datetime
from django.db import models
# Create your models here.
from django.db.models import ForeignKey
from django.utils.timezone import now


@python_2_unicode_compatible  # only if you need to support Python 2
class Product(models.Model):

    product_name = models.CharField(max_length=300, blank=True)
    official_price = models.DecimalField(default=0, decimal_places=5, max_digits=10)
    in_cart_number= models.IntegerField(default=0)

    def __str__(self):
        return self.product_name

@python_2_unicode_compatible  # only if you need to support Python 2
class Image(models.Model):

    related_to_product = ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="images", null=True, blank=True)
    name = models.CharField(max_length=300, default='default')

    def __str__(self):
        return self.name

djangoproj/mysite/shop/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect

from django.template import loader
from django.http import Http404
from django.urls import reverse
from django.db.models import F
from django.views import generic
from .models import Product, Image


def index(request):
    product_list=Product.objects.all()
    cart_sum = 0
    for product in product_list:
        cart_sum = cart_sum+product.in_cart_number
    context = {'product_list': product_list, 'cart_sum': cart_sum}
    return render(request, 'shop/index.html', context)


def bought(request):
    product_list=Product.objects.filter(in_cart_number__gte=1)
    total_price_dict={}
    for item in product_list:
        total_price_dict[item.id]=item.in_cart_number*item.official_price
    context = {'product_list': product_list, 'total_price_dict': total_price_dict}
    return render(request, 'shop/cart.html', context)


def add_to_cart(request):
    selected_prod = get_object_or_404(Product, pk=request.POST['product_bought'])

    product = get_object_or_404(Product, pk=selected_prod.id)
    product.in_cart_number = F('in_cart_number')+1
    product.save()
    return HttpResponseRedirect(reverse('shop:index'))

djangoproj/mysite/shop/templates/shop/cart.html
{% load static %}
{% load tags %}

<link rel="stylesheet" type="text/css" href="{% static 'shop/style.css' %}" />

<h1>Cart</h1>
{% for prod in product_list.all %}
    {% for item in prod.image_set.all %}
        <div class="floated_img">
        <img class="grid_img" src="{{item.image.url}}" alt="" >
        <p>Item price: {{prod.official_price}}<br>{{prod.product_name}}<br>Quantity: {{prod.in_cart_number}}
        <br>Total price: {{ total_price_dict|lookup:item.id }}
        </div>
    {% endfor %}
{% endfor %}

djangoproj/mysite/shop/templates/shop/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'shop/style.css' %}" />
<div class="float_right">
    <a href="{% url 'shop:bought' %}">My Cart</a>
    {{cart_sum}} items
</div>


<h1>Products available</h1>
{% for prod in product_list.all %}
    <div class="floated_img">
        <img class="grid_img" src="{{prod.image_set.all.0.image.url}}" alt="Image N/A" >
        <p>Price: {{prod.official_price}}<br>{{prod.product_name}}</p>

        <form action="{% url 'shop:add_to_cart' %}" method="post">
            {% csrf_token %}
            <button type="submit" name="product_bought" id="{{ prod.id }}" value="{{ prod.id }}">Add to cart</button>
        </form>
    </div>
{% endfor %}

djangoproj/mysite/shop/templates/shop/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>